runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php
  secure: always

- url: /top/.*
  script: index.php
  secure: always

- url: /new/.*
  script: index.php
  secure: always

- url: /ask/.*
  script: index.php
  secure: always

- url: /show/.*
  script: index.php
  secure: always

- url: /jobs/.*
  script: index.php
  secure: always

- url: /item/.*
  script: index.php
  secure: always
  
- url: /api/.*
  script: index.php

- url: /dist
  static_dir: dist

- url: /sw.js
  static_files: sw.js
  upload: sw.js

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json

- url: /images
  static_dir: images

- url: /js
  static_dir: js 

- url: /webcomponents
  static_dir: webcomponents

skip_files:
- node_modules/
